--[[============================================================================
Args-Controls.lua
 File generated by xStream - please see documentation for details
============================================================================]]--

return {
arguments = {
  {
      name = "value",
      value = 3.154,
      properties = {
          display_as = "value",
      },
  },
  {
      name = "hex",
      value = 48,
      properties = {
          min = 0,
          display_as = "hex",
          max = 65535,
      },
  },
  {
      name = "integer",
      value = 34,
      properties = {
          display_as = "integer",
      },
  },
  {
      name = "percent",
      value = 67.441860465116,
      properties = {
          min = -100,
          display_as = "percent",
          max = 100,
      },
  },
  {
      name = "note",
      value = 70.74688372093,
      properties = {
          min = 0,
          display_as = "note",
          max = 119,
      },
  },
  {
      name = "popup",
      value = 2,
      properties = {
          display_as = "popup",
          items = {
              "one",
              "two",
              "three",
          },
      },
  },
  {
      name = "chooser",
      value = 2,
      properties = {
          display_as = "chooser",
          items = {
              "one",
              "two",
              "three",
          },
      },
  },
  {
      name = "switch",
      value = 2,
      properties = {
          display_as = "switch",
          items = {
              "one",
              "two",
              "three",
          },
      },
  },
  {
      name = "minislider",
      value = -44222.813581395,
      properties = {
          display_as = "minislider",
      },
  },
  {
      name = "rotary",
      value = -39999.6,
      properties = {
          display_as = "rotary",
      },
  },
  {
      name = "boolean",
      value = true,
      properties = {
          display_as = "boolean",
      },
  },
  {
      name = "string",
      value = "this is another string",
      properties = {
          display_as = "string",
      },
  },
},
presets = {
  {
      hex = 1,
      note = 48,
      integer = 11,
      string = "this is a string",
      boolean = true,
      popup = 2,
      chooser = 1,
      minislider = 35999.64,
      value = 4,
      rotary = -39999.6,
      percent = 7.2,
      switch = 1,
  },
  {
      hex = 48,
      note = 70.74688372093,
      integer = 34,
      string = "this is another string",
      boolean = true,
      popup = 2,
      chooser = 2,
      minislider = -44222.813581395,
      value = 3.154,
      rotary = -39999.6,
      percent = 67.441860465116,
      switch = 2,
  },
},
data = {
},
options = {
 color = 0x60AACA,
},
callback = [[
-------------------------------------------------------------------------------
-- How to define arguments
-- A demonstration of the various visual components you can use for
-- controlling arguments. Expand the arguments panel below to see them all
-- at the same time, or click [models > magnifying glass] to reveal the 
-- location of the .lua file in which the actual arguments are defined)
-------------------------------------------------------------------------------
-- Name       Type      Supports      Requires  Restrict
--                      'zero_based'  property  to range
-- VALUE      number
-- HEX        number    yes
-- INTEGER    number    yes
-- PERCENT    number
-- NOTE       number                            1-119
-- POPUP      number                  items
-- CHOOSER    number                  items
-- SWITCH     number                  items
-- MINISLIDER number
-- ROTARY     number
-- BOOLEAN    boolean
-- STRING     string



]],
}