--[[============================================================================
Granular.lua
 File generated by xStream - please see documentation for details
============================================================================]]--

return {
arguments = {
  {
      name = "start",
      value = 43,
      properties = {
          min = 0,
          display_as = "hex",
          max = 255,
      },
  },
  {
      name = "duration",
      value = 27,
      properties = {
          min = 0,
          display_as = "hex",
          max = 255,
      },
      description = "duration of process",
  },
  {
      name = "tempo",
      value = 0.3,
      properties = {
          min = 0,
          max = 8,
      },
      description = "Speed factor (0.5 = half, 1 = normal, 2 = double speed)",
  },
  {
      name = "vol_rnd",
      value = 22.325581395349,
      properties = {
          min = 0,
          display_as = "percent",
          max = 100,
      },
      description = "Amount of noise applied to volume",
  },
  {
      name = "pan_rnd",
      value = 38.372093023256,
      properties = {
          min = 0,
          display_as = "percent",
          max = 100,
      },
      description = "Amount of noise applied to panning",
  },
  {
      name = "dly_rnd",
      value = 98.037209302326,
      properties = {
          min = 0,
          display_as = "percent",
          max = 100,
      },
      description = "Amount of noise applied to delay",
  },
  {
      name = "pitch_rnd",
      value = 0,
      properties = {
          min = 0,
          display_as = "percent",
          max = 100,
      },
      description = "Amount of detuning applied to notes",
  },
  {
      name = "offset_rnd",
      value = 8,
      properties = {
          min = 0,
          display_as = "percent",
          max = 100,
      },
      description = "Amount of noise applied to offset",
  },
  {
      name = "maybe_trig",
      value = 140,
      properties = {
          min = 0,
          display_as = "hex",
          max = 255,
      },
      description = "Probability that line is triggered",
  },
  {
      name = "pitch",
      value = 57.551720930233,
      properties = {
          max = 119,
          display_as = "note",
          min = 0,
      },
      description = "Note pitch",
  },
  {
      name = "instr_idx",
      value = 3,
      properties = {
          min = 1,
          max = 255,
          display_as = "hex",
          zero_based = true,
      },
      bind = "rns.selected_instrument_index_observable",
      description = "Specify the instrument number",
  },
  {
      name = "mode",
      value = 1,
      properties = {
          items = {
              "Forward",
              "Reverse",
              "Forward + 0Bxx",
              "Reverse + 0Bxx",
          },
      },
      description = "Playback mode",
  },
},
presets = {
  {
      pitch = 24.851627906977,
      pan_rnd = 76.920930232558,
      duration = 98,
      maybe_trig = 0,
      var2pitch = 1,
      pitch_rnd = 62.018604651163,
      offset_rnd = 0,
      instr_idx = 3,
      dly_rnd = 83.172093023256,
      start = 66,
      vol_rnd = 37.832558139535,
      mode = 1,
      tempo = 1,
  },
  {
      pitch = 38.644558139535,
      pan_rnd = 78.06511627907,
      duration = 10,
      maybe_trig = 23,
      var2pitch = 1,
      pitch_rnd = 0,
      offset_rnd = 13.032558139535,
      instr_idx = 3,
      dly_rnd = 73.972093023256,
      start = 42,
      vol_rnd = 82.558139534884,
      mode = 3,
      tempo = 0.1,
  },
  {
      pitch = 48.529860465116,
      pan_rnd = 57.051162790698,
      duration = 16,
      maybe_trig = 0,
      var2pitch = 1,
      pitch_rnd = 1.8139534883721,
      offset_rnd = 8,
      instr_idx = 3,
      dly_rnd = 5.7023255813953,
      start = 8,
      vol_rnd = 26.744186046512,
      mode = 3,
      tempo = 0.56111627906977,
  },
  {
      pitch = 41.511627906977,
      pan_rnd = 76.8,
      duration = 16,
      var2pitch = 1,
      pitch_rnd = 62.018604651163,
      offset_rnd = 0,
      instr_idx = 4,
      dly_rnd = 0,
      start = 0,
      vol_rnd = 1,
      mode = 1,
      tempo = 6,
  },
  {
      pitch = 41.511627906977,
      pan_rnd = 76.8,
      duration = 66,
      maybe_trig = 153,
      pitch_rnd = 90.33488372093,
      offset_rnd = 0,
      vol_rnd = 39.2,
      dly_rnd = 0,
      start = 4,
      mode = 1,
      instr_idx = 3,
      tempo = 5.6803720930233,
  },
  {
      pitch = 47.046511627907,
      pan_rnd = 7.5258644367809,
      duration = 102.1027253029,
      maybe_trig = 68.04773094882,
      pitch_rnd = 81.731620227668,
      offset_rnd = 31.922360911893,
      vol_rnd = 29.947813348796,
      dly_rnd = 31.82470168157,
      start = 243.51344340342,
      mode = 0,
      instr_idx = 3,
      tempo = 4.8053224280526,
  },
  {
      pitch = 49.725395348837,
      pan_rnd = 76.8,
      duration = 27,
      pitch_rnd = 84.455813953488,
      offset_rnd = 0,
      mode = 2,
      dly_rnd = 100,
      start = 43,
      vol_rnd = 100,
      instr_idx = 3,
      tempo = 0.3,
  },
  {
      pitch = 0,
      pan_rnd = 76.8,
      duration = 27,
      pitch_rnd = 84.455813953488,
      offset_rnd = 0,
      mode = 2,
      dly_rnd = 100,
      start = 43,
      vol_rnd = 100,
      instr_idx = 3,
      tempo = 0.3,
  },
  {
      pitch = 102.816,
      pan_rnd = 80,
      duration = 64,
      pitch_rnd = 80,
      offset_rnd = 0,
      mode = 2,
      dly_rnd = 8.4,
      start = 43,
      vol_rnd = 61.6,
      instr_idx = 3,
      tempo = 0.3,
  },
  {
      instr_idx = 3,
      pan_rnd = 38.372093023256,
      duration = 27,
      offset_rnd = 8,
      pitch_rnd = 0,
      maybe_trig = 140,
      mode = 1,
      dly_rnd = 98.037209302326,
      start = 43,
      vol_rnd = 22.325581395349,
      pitch = 57.551720930233,
      tempo = 0.3,
  },
},
data = {
  PLAYMODE = {
      REVERSE = 2,
      FORWARD = 1,
      FORWARD_Bxx = 3,
      REVERSE_Bxx = 4,
  },
},
options = {
 color = 0xF2D984,
},
callback = [[
-------------------------------------------------------------------------------
-- Granular model
-- Output: 1 note column (vol+pan+dly), multiple effect columns
-- Tip: Increase density by playing at higher speeds
-------------------------------------------------------------------------------

local forward = (args.mode == data.PLAYMODE.FORWARD)
  or (args.mode == data.PLAYMODE.FORWARD_Bxx)
local write_bxx = (args.mode == data.PLAYMODE.FORWARD_Bxx)
  or (args.mode == data.PLAYMODE.REVERSE_Bxx)
local my_xinc = forward and xinc or -xinc
local pos = args.start + (my_xinc*args.tempo)%args.duration
local sample_offset = pos + math.random(0,args.offset_rnd)
local pan_scaled = args.pan_rnd/100*0x40
local pan_rnd = math.random(-pan_scaled,pan_scaled)
local do_pitch = (args.pitch_rnd > 0)
local pitch_scaled = args.pitch_rnd/100*0xFF
local pitch_rnd = math.random(-pitch_scaled,pitch_scaled)
local volume_rnd = math.random(0,args.vol_rnd/100*0x80)
local delay_rnd = math.random(0,args.dly_rnd/100*0xFF)
--
xline.note_columns[1] = {
  note_value =args.pitch,
  instrument_value = args.instr_idx,
  volume_value = 0x80-volume_rnd,
  panning_value = (pan_rnd ~= 0) and 0x40+pan_rnd or 255,
  delay_value = (delay_rnd > 0) and delay_rnd or 0,
}
xline.effect_columns[1] = {
  number_string = "0S",
  amount_value = sample_offset%0xFF
}
xline.effect_columns[2] = {
  number_string = write_bxx and "0B" or "00",
  amount_string = write_bxx and "00" or "00"
}
xline.effect_columns[3] = {
  number_string = do_pitch and ((pitch_rnd > 0) 
    and "0U" or "0D") or "00",
  amount_value = do_pitch and ((pitch_rnd > 0) 
    and pitch_rnd or math.abs(pitch_rnd)) or 0
}
xline.effect_columns[4] = {
  number_string = (args.maybe_trig > 0) and "0Y" or "00",
  amount_value = args.maybe_trig
}



]],
}