--[[===========================================================================
Euclidean Rhythms.lua
===========================================================================]]--

return {
arguments = {
  {
      ["locked"] = false,
      ["name"] = "a.enabled",
      ["linked"] = false,
      ["value"] = true,
      ["properties"] = {
          ["display_as"] = "boolean",
      },
  },
  {
      ["locked"] = false,
      ["name"] = "transpose",
      ["linked"] = false,
      ["value"] = -7,
      ["properties"] = {
          ["max"] = 64,
          ["min"] = -64,
          ["display_as"] = "integer",
          ["zero_based"] = false,
      },
      ["description"] = "",
  },
  {
      ["poll"] = "rns.selected_phrase_index",
      ["locked"] = true,
      ["name"] = "phrase_idx",
      ["linked"] = false,
      ["value"] = 0,
      ["properties"] = {
          ["min"] = 0,
          ["max"] = 100,
          ["display_as"] = "hex",
          ["zero_based"] = false,
      },
      ["description"] = "",
  },
  {
      ["locked"] = false,
      ["name"] = "a.steps",
      ["linked"] = false,
      ["value"] = 16,
      ["properties"] = {
          ["max"] = 32,
          ["min"] = 1,
          ["display_as"] = "integer",
          ["zero_based"] = false,
      },
      ["description"] = "",
  },
  {
      ["locked"] = false,
      ["name"] = "a.pulses",
      ["linked"] = false,
      ["value"] = 6,
      ["properties"] = {
          ["max"] = 32,
          ["min"] = 1,
          ["display_as"] = "integer",
          ["zero_based"] = false,
      },
      ["description"] = "",
  },
  {
      ["locked"] = false,
      ["name"] = "a.offset",
      ["linked"] = false,
      ["value"] = 0,
      ["properties"] = {
          ["max"] = 16,
          ["min"] = -16,
          ["display_as"] = "integer",
          ["zero_based"] = false,
      },
      ["description"] = "",
  },
  {
      ["locked"] = false,
      ["name"] = "a.invert",
      ["linked"] = false,
      ["value"] = false,
      ["properties"] = {
          ["display_as"] = "checkbox",
      },
      ["description"] = "makes note-on become note-off and vice versa",
  },
  {
      ["locked"] = false,
      ["name"] = "a.pitch",
      ["linked"] = false,
      ["value"] = 61.129354520548,
      ["properties"] = {
          ["max"] = 119,
          ["display_as"] = "note",
          ["min"] = 0,
      },
      ["description"] = "",
  },
  {
      ["locked"] = false,
      ["name"] = "a.velocity",
      ["linked"] = false,
      ["value"] = 34.267716535433,
      ["properties"] = {
          ["min"] = 0,
          ["max"] = 128,
          ["display_as"] = "hex",
          ["zero_based"] = false,
      },
      ["description"] = "",
  },
  {
      ["locked"] = false,
      ["name"] = "a.column",
      ["linked"] = false,
      ["value"] = 1,
      ["properties"] = {
          ["min"] = 1,
          ["max"] = 12,
          ["display_as"] = "integer",
          ["zero_based"] = false,
      },
      ["description"] = "",
  },
  {
      ["locked"] = true,
      ["name"] = "a.instr",
      ["linked"] = true,
      ["value"] = 7,
      ["properties"] = {
          ["max"] = 255,
          ["min"] = 1,
          ["display_as"] = "hex",
          ["zero_based"] = true,
      },
      ["description"] = "",
  },
  {
      ["locked"] = false,
      ["name"] = "b.enabled",
      ["linked"] = false,
      ["value"] = false,
      ["properties"] = {
          ["display_as"] = "boolean",
      },
  },
  {
      ["locked"] = false,
      ["name"] = "b.steps",
      ["linked"] = false,
      ["value"] = 16,
      ["properties"] = {
          ["max"] = 32,
          ["min"] = 1,
          ["display_as"] = "integer",
          ["zero_based"] = false,
      },
      ["description"] = "",
  },
  {
      ["locked"] = false,
      ["name"] = "b.pulses",
      ["linked"] = false,
      ["value"] = 2,
      ["properties"] = {
          ["max"] = 32,
          ["min"] = 1,
          ["display_as"] = "integer",
          ["zero_based"] = false,
      },
      ["description"] = "",
  },
  {
      ["locked"] = false,
      ["name"] = "b.offset",
      ["linked"] = false,
      ["value"] = 4,
      ["properties"] = {
          ["max"] = 16,
          ["min"] = -16,
          ["display_as"] = "integer",
          ["zero_based"] = false,
      },
      ["description"] = "",
  },
  {
      ["locked"] = false,
      ["name"] = "b.invert",
      ["linked"] = false,
      ["value"] = false,
      ["properties"] = {
          ["display_as"] = "checkbox",
      },
      ["description"] = "makes note-on become note-off and vice versa",
  },
  {
      ["locked"] = false,
      ["name"] = "b.pitch",
      ["linked"] = false,
      ["value"] = 51.535433070866,
      ["properties"] = {
          ["max"] = 119,
          ["display_as"] = "note",
          ["min"] = 0,
      },
      ["description"] = "",
  },
  {
      ["locked"] = false,
      ["name"] = "b.velocity",
      ["linked"] = false,
      ["value"] = 39.307086614173,
      ["properties"] = {
          ["min"] = 0,
          ["max"] = 128,
          ["display_as"] = "hex",
          ["zero_based"] = false,
      },
      ["description"] = "",
  },
  {
      ["locked"] = false,
      ["name"] = "b.column",
      ["linked"] = false,
      ["value"] = 2,
      ["properties"] = {
          ["min"] = 1,
          ["max"] = 12,
          ["display_as"] = "integer",
          ["zero_based"] = false,
      },
      ["description"] = "",
  },
  {
      ["locked"] = true,
      ["name"] = "b.instr",
      ["linked"] = true,
      ["value"] = 3,
      ["properties"] = {
          ["max"] = 255,
          ["min"] = 1,
          ["display_as"] = "hex",
          ["zero_based"] = true,
      },
      ["description"] = "",
  },
  {
      ["locked"] = false,
      ["name"] = "c.enabled",
      ["linked"] = false,
      ["value"] = false,
      ["properties"] = {
          ["display_as"] = "boolean",
      },
  },
  {
      ["locked"] = false,
      ["name"] = "c.steps",
      ["linked"] = false,
      ["value"] = 11,
      ["properties"] = {
          ["max"] = 32,
          ["min"] = 1,
          ["display_as"] = "integer",
          ["zero_based"] = false,
      },
      ["description"] = "",
  },
  {
      ["locked"] = false,
      ["name"] = "c.pulses",
      ["linked"] = false,
      ["value"] = 4,
      ["properties"] = {
          ["max"] = 32,
          ["min"] = 1,
          ["display_as"] = "integer",
          ["zero_based"] = false,
      },
      ["description"] = "",
  },
  {
      ["locked"] = false,
      ["name"] = "c.offset",
      ["linked"] = false,
      ["value"] = 1,
      ["properties"] = {
          ["max"] = 16,
          ["min"] = -16,
          ["display_as"] = "integer",
          ["zero_based"] = false,
      },
      ["description"] = "",
  },
  {
      ["locked"] = false,
      ["name"] = "c.invert",
      ["linked"] = false,
      ["value"] = false,
      ["properties"] = {
          ["display_as"] = "checkbox",
      },
      ["description"] = "makes note-on become note-off and vice versa",
  },
  {
      ["locked"] = false,
      ["name"] = "c.pitch",
      ["linked"] = false,
      ["value"] = 58.822056062992,
      ["properties"] = {
          ["max"] = 119,
          ["display_as"] = "note",
          ["min"] = 0,
      },
      ["description"] = "",
  },
  {
      ["locked"] = false,
      ["name"] = "c.velocity",
      ["linked"] = false,
      ["value"] = 38.299212598425,
      ["properties"] = {
          ["min"] = 0,
          ["max"] = 128,
          ["display_as"] = "hex",
          ["zero_based"] = false,
      },
      ["description"] = "",
  },
  {
      ["locked"] = false,
      ["name"] = "c.column",
      ["linked"] = false,
      ["value"] = 3,
      ["properties"] = {
          ["min"] = 1,
          ["max"] = 12,
          ["display_as"] = "integer",
          ["zero_based"] = false,
      },
      ["description"] = "",
  },
  {
      ["locked"] = true,
      ["name"] = "c.instr",
      ["linked"] = true,
      ["value"] = 3,
      ["properties"] = {
          ["max"] = 255,
          ["min"] = 1,
          ["display_as"] = "hex",
          ["zero_based"] = true,
      },
      ["description"] = "",
  },
  {
      ["locked"] = false,
      ["name"] = "d.enabled",
      ["linked"] = false,
      ["value"] = false,
      ["properties"] = {
          ["display_as"] = "boolean",
      },
  },
  {
      ["locked"] = false,
      ["name"] = "d.steps",
      ["linked"] = false,
      ["value"] = 14,
      ["properties"] = {
          ["max"] = 32,
          ["min"] = 1,
          ["display_as"] = "integer",
          ["zero_based"] = false,
      },
      ["description"] = "",
  },
  {
      ["locked"] = false,
      ["name"] = "d.pulses",
      ["linked"] = false,
      ["value"] = 4,
      ["properties"] = {
          ["max"] = 32,
          ["min"] = 1,
          ["display_as"] = "integer",
          ["zero_based"] = false,
      },
      ["description"] = "",
  },
  {
      ["locked"] = false,
      ["name"] = "d.offset",
      ["linked"] = false,
      ["value"] = 0,
      ["properties"] = {
          ["max"] = 16,
          ["min"] = -16,
          ["display_as"] = "integer",
          ["zero_based"] = false,
      },
      ["description"] = "",
  },
  {
      ["locked"] = false,
      ["name"] = "d.invert",
      ["linked"] = false,
      ["value"] = false,
      ["properties"] = {
          ["display_as"] = "checkbox",
      },
      ["description"] = "makes note-on become note-off and vice versa",
  },
  {
      ["locked"] = false,
      ["name"] = "d.pitch",
      ["linked"] = false,
      ["value"] = 27.173228346457,
      ["properties"] = {
          ["max"] = 119,
          ["display_as"] = "note",
          ["min"] = 0,
      },
      ["description"] = "",
  },
  {
      ["locked"] = false,
      ["name"] = "d.velocity",
      ["linked"] = false,
      ["value"] = 51.40157480315,
      ["properties"] = {
          ["min"] = 0,
          ["max"] = 128,
          ["display_as"] = "hex",
          ["zero_based"] = false,
      },
      ["description"] = "",
  },
  {
      ["locked"] = false,
      ["name"] = "d.column",
      ["linked"] = false,
      ["value"] = 4,
      ["properties"] = {
          ["min"] = 1,
          ["max"] = 12,
          ["display_as"] = "integer",
          ["zero_based"] = false,
      },
      ["description"] = "",
  },
  {
      ["locked"] = true,
      ["name"] = "d.instr",
      ["linked"] = true,
      ["value"] = 3,
      ["properties"] = {
          ["max"] = 255,
          ["min"] = 1,
          ["display_as"] = "hex",
          ["zero_based"] = true,
      },
      ["description"] = "",
  },
  {
      ["locked"] = false,
      ["name"] = "e.enabled",
      ["linked"] = false,
      ["value"] = false,
      ["properties"] = {
          ["display_as"] = "boolean",
      },
  },
  {
      ["locked"] = false,
      ["name"] = "e.steps",
      ["linked"] = false,
      ["value"] = 13,
      ["properties"] = {
          ["max"] = 32,
          ["min"] = 1,
          ["display_as"] = "integer",
          ["zero_based"] = false,
      },
      ["description"] = "",
  },
  {
      ["locked"] = false,
      ["name"] = "e.pulses",
      ["linked"] = false,
      ["value"] = 5,
      ["properties"] = {
          ["max"] = 32,
          ["min"] = 1,
          ["display_as"] = "integer",
          ["zero_based"] = false,
      },
      ["description"] = "",
  },
  {
      ["locked"] = false,
      ["name"] = "e.offset",
      ["linked"] = false,
      ["value"] = 0,
      ["properties"] = {
          ["max"] = 16,
          ["min"] = -16,
          ["display_as"] = "integer",
          ["zero_based"] = false,
      },
      ["description"] = "",
  },
  {
      ["locked"] = false,
      ["name"] = "e.invert",
      ["linked"] = false,
      ["value"] = false,
      ["properties"] = {
          ["display_as"] = "checkbox",
      },
      ["description"] = "makes note-on become note-off and vice versa",
  },
  {
      ["locked"] = false,
      ["name"] = "e.pitch",
      ["linked"] = false,
      ["value"] = 54.346456692913,
      ["properties"] = {
          ["max"] = 119,
          ["display_as"] = "note",
          ["min"] = 0,
      },
      ["description"] = "",
  },
  {
      ["locked"] = false,
      ["name"] = "e.velocity",
      ["linked"] = false,
      ["value"] = 42.330708661417,
      ["properties"] = {
          ["min"] = 0,
          ["max"] = 128,
          ["display_as"] = "hex",
          ["zero_based"] = false,
      },
      ["description"] = "",
  },
  {
      ["locked"] = false,
      ["name"] = "e.column",
      ["linked"] = false,
      ["value"] = 5,
      ["properties"] = {
          ["min"] = 1,
          ["max"] = 12,
          ["display_as"] = "integer",
          ["zero_based"] = false,
      },
      ["description"] = "",
  },
  {
      ["locked"] = true,
      ["name"] = "e.instr",
      ["linked"] = true,
      ["value"] = 3,
      ["properties"] = {
          ["max"] = 255,
          ["min"] = 1,
          ["display_as"] = "hex",
          ["zero_based"] = true,
      },
      ["description"] = "",
  },
},
presets = {
  {
      ["e.offset"] = 0,
      ["c.offset"] = 1,
      ["d.offset"] = 0,
      ["a.offset"] = 0,
      ["b.offset"] = 4,
      ["e.enabled"] = true,
      ["d.enabled"] = true,
      ["c.enabled"] = true,
      ["b.enabled"] = true,
      ["a.enabled"] = true,
      ["a.invert"] = false,
      ["b.invert"] = false,
      ["c.invert"] = false,
      ["d.invert"] = false,
      ["e.invert"] = true,
      ["a.instr"] = 1,
      ["c.pulses"] = 4,
      ["b.pulses"] = 2,
      ["e.pulses"] = 5,
      ["d.pulses"] = 4,
      ["c.instr"] = 1,
      ["b.instr"] = 1,
      ["b.column"] = 2,
      ["a.velocity"] = 34.267716535433,
      ["b.pitch"] = 51.535433070866,
      ["c.pitch"] = 59.031496062992,
      ["d.pitch"] = 35.606299212598,
      ["e.pitch"] = 63.716535433071,
      ["c.steps"] = 11,
      ["d.steps"] = 14,
      ["e.steps"] = 13,
      ["e.velocity"] = 22.173228346457,
      ["a.steps"] = 16,
      ["c.velocity"] = 44.346456692913,
      ["name"] = "",
      ["e.column"] = 5,
      ["d.instr"] = 1,
      ["d.column"] = 4,
      ["d.velocity"] = 53.417322834646,
      ["b.velocity"] = 56.44094488189,
      ["a.pitch"] = 44.03937007874,
      ["b.steps"] = 16,
      ["a.column"] = 1,
      ["a.pulses"] = 6,
      ["c.column"] = 3,
      ["e.instr"] = 1,
      ["phrase_idx"] = 11,
  },
  {
      ["e.offset"] = 0,
      ["c.offset"] = 1,
      ["d.offset"] = 0,
      ["a.offset"] = 0,
      ["b.offset"] = 4,
      ["e.enabled"] = true,
      ["d.enabled"] = true,
      ["c.enabled"] = true,
      ["b.enabled"] = true,
      ["a.enabled"] = true,
      ["a.invert"] = false,
      ["b.invert"] = false,
      ["c.invert"] = false,
      ["d.invert"] = true,
      ["e.invert"] = true,
      ["a.instr"] = 1,
      ["c.pulses"] = 4,
      ["b.pulses"] = 2,
      ["e.pulses"] = 5,
      ["d.pulses"] = 4,
      ["c.instr"] = 1,
      ["b.instr"] = 1,
      ["b.column"] = 2,
      ["a.velocity"] = 40.314960629921,
      ["b.pitch"] = 51.535433070866,
      ["c.pitch"] = 58.094488188976,
      ["d.pitch"] = 34.669291338583,
      ["e.pitch"] = 63.716535433071,
      ["c.steps"] = 11,
      ["d.steps"] = 14,
      ["e.steps"] = 13,
      ["e.velocity"] = 22.173228346457,
      ["a.steps"] = 16,
      ["c.velocity"] = 46.362204724409,
      ["name"] = "",
      ["e.column"] = 5,
      ["d.instr"] = 1,
      ["d.column"] = 4,
      ["d.velocity"] = 34.267716535433,
      ["b.velocity"] = 56.44094488189,
      ["a.pitch"] = 42.165354330709,
      ["b.steps"] = 16,
      ["a.column"] = 1,
      ["a.pulses"] = 6,
      ["c.column"] = 3,
      ["e.instr"] = 1,
      ["phrase_idx"] = 11,
  },
  {
      ["e.offset"] = 0,
      ["c.offset"] = 1,
      ["d.offset"] = 0,
      ["a.offset"] = 0,
      ["b.offset"] = 4,
      ["e.enabled"] = true,
      ["d.enabled"] = true,
      ["c.enabled"] = true,
      ["b.enabled"] = true,
      ["a.enabled"] = true,
      ["a.invert"] = false,
      ["b.invert"] = false,
      ["c.invert"] = false,
      ["d.invert"] = false,
      ["e.invert"] = false,
      ["a.instr"] = 1,
      ["c.pulses"] = 4,
      ["b.pulses"] = 2,
      ["e.pulses"] = 5,
      ["d.pulses"] = 4,
      ["c.instr"] = 1,
      ["b.instr"] = 1,
      ["b.column"] = 2,
      ["a.velocity"] = 34.267716535433,
      ["b.pitch"] = 51.535433070866,
      ["c.pitch"] = 58.822056062992,
      ["d.pitch"] = 27.173228346457,
      ["e.pitch"] = 54.346456692913,
      ["c.steps"] = 11,
      ["d.steps"] = 14,
      ["e.steps"] = 13,
      ["e.velocity"] = 42.330708661417,
      ["a.steps"] = 16,
      ["c.velocity"] = 38.299212598425,
      ["name"] = "",
      ["e.column"] = 5,
      ["d.instr"] = 1,
      ["d.column"] = 4,
      ["d.velocity"] = 51.40157480315,
      ["b.velocity"] = 39.307086614173,
      ["a.pitch"] = 46.850393700787,
      ["b.steps"] = 16,
      ["a.column"] = 1,
      ["a.pulses"] = 6,
      ["c.column"] = 3,
      ["e.instr"] = 1,
      ["phrase_idx"] = 11,
  },
  {
      ["e.offset"] = 0,
      ["c.offset"] = 1,
      ["d.offset"] = 0,
      ["a.offset"] = 0,
      ["b.offset"] = 4,
      ["e.enabled"] = true,
      ["d.enabled"] = true,
      ["c.enabled"] = true,
      ["b.enabled"] = true,
      ["a.enabled"] = true,
      ["a.invert"] = false,
      ["b.invert"] = false,
      ["c.invert"] = false,
      ["d.invert"] = false,
      ["e.invert"] = true,
      ["a.instr"] = 1,
      ["c.pulses"] = 4,
      ["b.pulses"] = 2,
      ["e.pulses"] = 5,
      ["d.pulses"] = 4,
      ["c.instr"] = 1,
      ["b.instr"] = 1,
      ["b.column"] = 2,
      ["a.velocity"] = 38.299212598425,
      ["b.pitch"] = 47.787401574803,
      ["c.pitch"] = 59.968503937008,
      ["d.pitch"] = 30.92125984252,
      ["e.pitch"] = 44.03937007874,
      ["c.steps"] = 11,
      ["d.steps"] = 14,
      ["e.steps"] = 13,
      ["e.velocity"] = 32.251968503937,
      ["a.steps"] = 16,
      ["c.velocity"] = 44.346456692913,
      ["name"] = "",
      ["e.column"] = 5,
      ["d.instr"] = 1,
      ["d.column"] = 4,
      ["d.velocity"] = 59.464566929134,
      ["b.velocity"] = 56.44094488189,
      ["a.pitch"] = 39.354330708661,
      ["b.steps"] = 16,
      ["a.column"] = 1,
      ["a.pulses"] = 6,
      ["c.column"] = 3,
      ["e.instr"] = 1,
      ["phrase_idx"] = 11,
  },
  {
      ["e.offset"] = 0,
      ["c.offset"] = 1,
      ["d.offset"] = 0,
      ["a.offset"] = 2,
      ["b.offset"] = 4,
      ["e.enabled"] = true,
      ["d.enabled"] = true,
      ["c.enabled"] = true,
      ["b.enabled"] = true,
      ["a.enabled"] = true,
      ["a.invert"] = false,
      ["b.invert"] = false,
      ["c.invert"] = false,
      ["d.invert"] = false,
      ["e.invert"] = false,
      ["a.instr"] = 1,
      ["c.pulses"] = 4,
      ["b.pulses"] = 2,
      ["e.pulses"] = 5,
      ["d.pulses"] = 4,
      ["c.instr"] = 1,
      ["b.instr"] = 1,
      ["b.column"] = 2,
      ["a.velocity"] = 38.299212598425,
      ["b.pitch"] = 47.787401574803,
      ["c.pitch"] = 59.968503937008,
      ["d.pitch"] = 32.795275590551,
      ["e.pitch"] = 44.976377952756,
      ["c.steps"] = 11,
      ["d.steps"] = 14,
      ["e.steps"] = 13,
      ["e.velocity"] = 23.181102362205,
      ["a.steps"] = 16,
      ["c.velocity"] = 44.346456692913,
      ["name"] = "",
      ["e.column"] = 5,
      ["d.instr"] = 1,
      ["d.column"] = 4,
      ["d.velocity"] = 59.464566929134,
      ["b.velocity"] = 56.44094488189,
      ["a.pitch"] = 39.754170708661,
      ["b.steps"] = 16,
      ["a.column"] = 1,
      ["a.pulses"] = 6,
      ["c.column"] = 3,
      ["e.instr"] = 1,
      ["phrase_idx"] = 11,
  },
  {
      ["e.offset"] = 0,
      ["c.offset"] = 1,
      ["d.offset"] = 0,
      ["a.offset"] = 2,
      ["b.offset"] = 4,
      ["e.enabled"] = true,
      ["d.enabled"] = true,
      ["c.enabled"] = true,
      ["b.enabled"] = true,
      ["a.enabled"] = true,
      ["a.invert"] = false,
      ["b.invert"] = true,
      ["c.invert"] = false,
      ["d.invert"] = false,
      ["e.invert"] = false,
      ["a.instr"] = 1,
      ["c.pulses"] = 4,
      ["b.pulses"] = 2,
      ["e.pulses"] = 5,
      ["d.pulses"] = 4,
      ["c.instr"] = 1,
      ["b.instr"] = 1,
      ["b.column"] = 2,
      ["a.velocity"] = 38.417322834646,
      ["b.pitch"] = 51.535433070866,
      ["c.pitch"] = 58.094488188976,
      ["d.pitch"] = 34.669291338583,
      ["e.pitch"] = 54.346456692913,
      ["c.steps"] = 11,
      ["d.steps"] = 14,
      ["e.steps"] = 13,
      ["e.velocity"] = 40.314960629921,
      ["a.steps"] = 24,
      ["c.velocity"] = 40.314960629921,
      ["name"] = "",
      ["e.column"] = 5,
      ["d.instr"] = 1,
      ["d.column"] = 4,
      ["d.velocity"] = 56.44094488189,
      ["b.velocity"] = 25.44094488189,
      ["a.pitch"] = 39.123287671233,
      ["b.steps"] = 16,
      ["a.column"] = 1,
      ["a.pulses"] = 6,
      ["c.column"] = 3,
      ["e.instr"] = 1,
      ["phrase_idx"] = 11,
  },
  {
      ["e.offset"] = 0,
      ["c.offset"] = 1,
      ["d.offset"] = 0,
      ["a.offset"] = 0,
      ["b.offset"] = 4,
      ["e.enabled"] = true,
      ["d.enabled"] = true,
      ["c.enabled"] = true,
      ["b.enabled"] = true,
      ["a.enabled"] = true,
      ["a.invert"] = false,
      ["b.invert"] = false,
      ["c.invert"] = false,
      ["d.invert"] = false,
      ["e.invert"] = true,
      ["a.instr"] = 1,
      ["c.pulses"] = 4,
      ["b.pulses"] = 2,
      ["e.pulses"] = 5,
      ["d.pulses"] = 4,
      ["c.instr"] = 1,
      ["b.instr"] = 1,
      ["b.column"] = 2,
      ["a.velocity"] = 34.267716535433,
      ["b.pitch"] = 47.446330708661,
      ["c.pitch"] = 59.031496062992,
      ["d.pitch"] = 32.795275590551,
      ["e.pitch"] = 56.220472440945,
      ["c.steps"] = 11,
      ["d.steps"] = 14,
      ["e.steps"] = 13,
      ["e.velocity"] = 22.173228346457,
      ["a.steps"] = 16,
      ["c.velocity"] = 44.346456692913,
      ["name"] = "",
      ["e.column"] = 5,
      ["d.instr"] = 1,
      ["d.column"] = 4,
      ["d.velocity"] = 53.417322834646,
      ["b.velocity"] = 31.44094488189,
      ["a.pitch"] = 47.787401574803,
      ["b.steps"] = 16,
      ["a.column"] = 1,
      ["a.pulses"] = 6,
      ["c.column"] = 3,
      ["e.instr"] = 1,
      ["phrase_idx"] = 4,
  },
  {
      ["e.offset"] = 0,
      ["c.offset"] = 1,
      ["d.offset"] = 0,
      ["a.offset"] = 0,
      ["b.offset"] = 4,
      ["e.enabled"] = true,
      ["d.enabled"] = true,
      ["c.enabled"] = true,
      ["b.enabled"] = true,
      ["a.enabled"] = true,
      ["a.invert"] = false,
      ["b.invert"] = false,
      ["c.invert"] = false,
      ["d.invert"] = true,
      ["e.invert"] = true,
      ["a.instr"] = 1,
      ["c.pulses"] = 4,
      ["b.pulses"] = 2,
      ["e.pulses"] = 5,
      ["d.pulses"] = 4,
      ["c.instr"] = 1,
      ["b.instr"] = 1,
      ["b.column"] = 2,
      ["a.velocity"] = 40.314960629921,
      ["b.pitch"] = 51.535433070866,
      ["c.pitch"] = 59.031496062992,
      ["d.pitch"] = 35.606299212598,
      ["e.pitch"] = 63.716535433071,
      ["c.steps"] = 11,
      ["d.steps"] = 14,
      ["e.steps"] = 13,
      ["e.velocity"] = 22.173228346457,
      ["a.steps"] = 16,
      ["c.velocity"] = 46.362204724409,
      ["name"] = "",
      ["e.column"] = 5,
      ["d.instr"] = 1,
      ["d.column"] = 4,
      ["d.velocity"] = 34.267716535433,
      ["b.velocity"] = 56.44094488189,
      ["a.pitch"] = 42.165354330709,
      ["b.steps"] = 16,
      ["a.column"] = 1,
      ["a.pulses"] = 6,
      ["c.column"] = 3,
      ["e.instr"] = 1,
      ["phrase_idx"] = 2,
  },
  {
      ["e.offset"] = 0,
      ["c.offset"] = 1,
      ["d.offset"] = 0,
      ["a.offset"] = 0,
      ["b.offset"] = 4,
      ["e.enabled"] = true,
      ["d.enabled"] = true,
      ["c.enabled"] = true,
      ["b.enabled"] = true,
      ["a.enabled"] = true,
      ["a.invert"] = false,
      ["b.invert"] = false,
      ["c.invert"] = false,
      ["d.invert"] = true,
      ["e.invert"] = true,
      ["a.instr"] = 1,
      ["c.pulses"] = 4,
      ["b.pulses"] = 2,
      ["e.pulses"] = 5,
      ["d.pulses"] = 4,
      ["c.instr"] = 1,
      ["b.instr"] = 1,
      ["b.column"] = 2,
      ["a.velocity"] = 49.385826771654,
      ["b.pitch"] = 61.842519685039,
      ["c.pitch"] = 59.031496062992,
      ["d.pitch"] = 37.48031496063,
      ["e.pitch"] = 52.472440944882,
      ["c.steps"] = 11,
      ["d.steps"] = 14,
      ["e.steps"] = 13,
      ["e.velocity"] = 34.267716535433,
      ["a.steps"] = 16,
      ["c.velocity"] = 43.338582677165,
      ["name"] = "",
      ["e.column"] = 5,
      ["d.instr"] = 1,
      ["d.column"] = 4,
      ["d.velocity"] = 38.299212598425,
      ["b.velocity"] = 55.433070866142,
      ["a.pitch"] = 25.299212598425,
      ["b.steps"] = 16,
      ["a.column"] = 1,
      ["a.pulses"] = 6,
      ["c.column"] = 3,
      ["e.instr"] = 1,
      ["phrase_idx"] = 4,
  },
  {
      ["e.offset"] = 0,
      ["c.offset"] = 1,
      ["d.offset"] = 0,
      ["a.offset"] = 0,
      ["b.offset"] = 4,
      ["e.enabled"] = true,
      ["d.enabled"] = true,
      ["c.enabled"] = true,
      ["b.enabled"] = true,
      ["a.enabled"] = true,
      ["a.invert"] = false,
      ["b.invert"] = false,
      ["c.invert"] = false,
      ["d.invert"] = true,
      ["e.invert"] = true,
      ["a.instr"] = 1,
      ["c.pulses"] = 4,
      ["b.pulses"] = 2,
      ["e.pulses"] = 5,
      ["d.pulses"] = 4,
      ["c.instr"] = 1,
      ["b.instr"] = 1,
      ["b.column"] = 2,
      ["a.velocity"] = 40.314960629921,
      ["b.pitch"] = 61.842519685039,
      ["c.pitch"] = 45.913385826772,
      ["d.pitch"] = 37.48031496063,
      ["e.pitch"] = 49.661417322835,
      ["c.steps"] = 11,
      ["d.steps"] = 14,
      ["e.steps"] = 13,
      ["e.velocity"] = 35.275590551181,
      ["a.steps"] = 16,
      ["c.velocity"] = 43.338582677165,
      ["name"] = "",
      ["e.column"] = 5,
      ["d.instr"] = 1,
      ["d.column"] = 4,
      ["d.velocity"] = 38.299212598425,
      ["b.velocity"] = 42.330708661417,
      ["a.pitch"] = 40.291338582677,
      ["b.steps"] = 16,
      ["a.column"] = 1,
      ["a.pulses"] = 6,
      ["c.column"] = 3,
      ["e.instr"] = 1,
      ["phrase_idx"] = 4,
  },
  {
      ["e.offset"] = 16,
      ["c.offset"] = 1,
      ["d.offset"] = 0,
      ["a.offset"] = 0,
      ["b.offset"] = 4,
      ["e.enabled"] = true,
      ["d.enabled"] = true,
      ["c.enabled"] = true,
      ["b.enabled"] = true,
      ["a.enabled"] = true,
      ["a.invert"] = false,
      ["b.invert"] = false,
      ["c.invert"] = false,
      ["d.invert"] = true,
      ["e.invert"] = true,
      ["a.instr"] = 1,
      ["c.pulses"] = 4,
      ["b.pulses"] = 2,
      ["e.pulses"] = 5,
      ["d.pulses"] = 4,
      ["c.instr"] = 1,
      ["b.instr"] = 1,
      ["b.column"] = 2,
      ["a.velocity"] = 40.314960629921,
      ["b.pitch"] = 61.842519685039,
      ["c.pitch"] = 45.913385826772,
      ["d.pitch"] = 37.48031496063,
      ["e.pitch"] = 49.661417322835,
      ["c.steps"] = 22,
      ["d.steps"] = 28,
      ["e.steps"] = 26,
      ["e.velocity"] = 35.275590551181,
      ["a.steps"] = 32,
      ["c.velocity"] = 43.338582677165,
      ["name"] = "",
      ["e.column"] = 5,
      ["d.instr"] = 1,
      ["d.column"] = 4,
      ["d.velocity"] = 38.299212598425,
      ["b.velocity"] = 42.330708661417,
      ["a.pitch"] = 40.291338582677,
      ["b.steps"] = 32,
      ["a.column"] = 1,
      ["a.pulses"] = 6,
      ["c.column"] = 3,
      ["e.instr"] = 1,
      ["phrase_idx"] = 11,
  },
  {
      ["e.offset"] = 16,
      ["c.offset"] = 1,
      ["d.offset"] = 0,
      ["a.offset"] = 0,
      ["b.offset"] = 4,
      ["e.enabled"] = true,
      ["d.enabled"] = true,
      ["c.enabled"] = true,
      ["b.enabled"] = true,
      ["a.enabled"] = true,
      ["a.invert"] = false,
      ["b.invert"] = false,
      ["c.invert"] = false,
      ["d.invert"] = true,
      ["e.invert"] = true,
      ["a.instr"] = 2,
      ["c.pulses"] = 4,
      ["b.pulses"] = 2,
      ["e.pulses"] = 5,
      ["d.pulses"] = 4,
      ["c.instr"] = 2,
      ["b.instr"] = 2,
      ["b.column"] = 2,
      ["a.velocity"] = 0,
      ["b.pitch"] = 45.913385826772,
      ["c.pitch"] = 45.913385826772,
      ["d.pitch"] = 37.48031496063,
      ["e.pitch"] = 49.661417322835,
      ["c.steps"] = 22,
      ["d.steps"] = 28,
      ["e.steps"] = 26,
      ["e.velocity"] = 35.275590551181,
      ["a.steps"] = 32,
      ["c.velocity"] = 76.59842519685,
      ["name"] = "",
      ["e.column"] = 5,
      ["d.instr"] = 2,
      ["d.column"] = 4,
      ["d.velocity"] = 35.275590551181,
      ["b.velocity"] = 62.488188976378,
      ["a.pitch"] = 40.291338582677,
      ["b.steps"] = 32,
      ["a.column"] = 1,
      ["a.pulses"] = 6,
      ["c.column"] = 3,
      ["e.instr"] = 2,
      ["phrase_idx"] = 0,
  },
  {
      ["e.offset"] = 0,
      ["c.offset"] = 1,
      ["d.offset"] = 0,
      ["a.offset"] = 0,
      ["b.offset"] = 4,
      ["e.enabled"] = true,
      ["d.enabled"] = true,
      ["c.enabled"] = true,
      ["b.enabled"] = true,
      ["a.enabled"] = true,
      ["transpose"] = -17,
      ["a.invert"] = false,
      ["b.invert"] = false,
      ["c.invert"] = false,
      ["d.invert"] = true,
      ["e.invert"] = true,
      ["a.instr"] = 3,
      ["c.pulses"] = 4,
      ["b.pulses"] = 2,
      ["e.pulses"] = 5,
      ["d.pulses"] = 4,
      ["c.instr"] = 3,
      ["b.instr"] = 3,
      ["b.column"] = 2,
      ["a.pitch"] = 40.291338582677,
      ["b.pitch"] = 61.842519685039,
      ["c.pitch"] = 45.913385826772,
      ["d.pitch"] = 37.48031496063,
      ["e.pitch"] = 49.661417322835,
      ["c.steps"] = 11,
      ["d.steps"] = 14,
      ["e.steps"] = 13,
      ["e.velocity"] = 35.275590551181,
      ["a.steps"] = 16,
      ["b.steps"] = 16,
      ["name"] = "",
      ["e.column"] = 5,
      ["d.instr"] = 3,
      ["d.column"] = 4,
      ["d.velocity"] = 38.299212598425,
      ["b.velocity"] = 42.330708661417,
      ["a.velocity"] = 40.314960629921,
      ["a.column"] = 1,
      ["a.pulses"] = 6,
      ["c.column"] = 3,
      ["c.velocity"] = 43.338582677165,
      ["e.instr"] = 3,
      ["phrase_idx"] = 0,
  },
  {
      ["e.offset"] = 16,
      ["c.offset"] = 1,
      ["d.offset"] = 0,
      ["a.offset"] = 0,
      ["b.offset"] = 2,
      ["e.enabled"] = true,
      ["d.enabled"] = true,
      ["c.enabled"] = true,
      ["b.enabled"] = true,
      ["a.enabled"] = true,
      ["transpose"] = -17,
      ["a.invert"] = false,
      ["b.invert"] = false,
      ["c.invert"] = false,
      ["d.invert"] = true,
      ["e.invert"] = true,
      ["a.instr"] = 3,
      ["c.pulses"] = 4,
      ["b.pulses"] = 4,
      ["e.pulses"] = 5,
      ["d.pulses"] = 4,
      ["c.instr"] = 3,
      ["b.instr"] = 3,
      ["b.column"] = 2,
      ["a.pitch"] = 40.291338582677,
      ["b.pitch"] = 45.913385826772,
      ["c.pitch"] = 45.913385826772,
      ["d.pitch"] = 37.48031496063,
      ["e.pitch"] = 49.661417322835,
      ["c.steps"] = 22,
      ["d.steps"] = 28,
      ["e.steps"] = 26,
      ["e.velocity"] = 35.275590551181,
      ["a.steps"] = 16,
      ["b.steps"] = 16,
      ["name"] = "",
      ["e.column"] = 5,
      ["d.instr"] = 3,
      ["d.column"] = 4,
      ["d.velocity"] = 35.275590551181,
      ["b.velocity"] = 62.488188976378,
      ["a.velocity"] = 0,
      ["a.column"] = 1,
      ["a.pulses"] = 6,
      ["c.column"] = 3,
      ["c.velocity"] = 76.59842519685,
      ["e.instr"] = 3,
      ["phrase_idx"] = 0,
  },
},
data = {
},
events = {
},
options = {
 color = 0x505552,
},
callback = [[
-------------------------------------------------------------------------------
-- Euclidean Rhythms
-------------------------------------------------------------------------------

local generate = function(steps,pulses,offset,invert,pitch,velocity,column,instr_idx)
  local rslt = nil
  local step_size = steps/pulses
  local position = (xinc%steps)
  local pulses_table = {}
  for k = 0,(pulses-1) do
    local pulse = math.ceil(step_size * k)+offset
    table.insert(pulses_table,pulse % steps)
  end
  local do_output = table.find(pulses_table,position)
  if invert then 
    do_output = not do_output 
  end
  if do_output then
    --print(instr)
    xline.note_columns[column] = {
      note_value = pitch + args.transpose,
      volume_value = velocity == 0x80 and EMPTY_VOLUME_VALUE or velocity,
      instrument_value = instr_idx,
    }
  else
    xline.note_columns[column] = {}
  end
  if (args.phrase_idx == 0) then
    xline.effect_columns[1] = {
      number_string = "00",
      amount_value = 0
    }
  else
    xline.effect_columns[1] = {
      number_string = "0Z",
      amount_value = args.phrase_idx or 0,
    }
  end

end

local tabs = {"a","b","c","d","e"}
for k,v in ipairs(tabs) do

  if (args[v].enabled) then
    generate(args[v].steps,
      args[v].pulses,
      args[v].offset,
      args[v].invert,
      args[v].pitch,
      args[v].velocity,
      args[v].column,
      args[v].instr)
      
  end

end
]],
}